### ISSUE TITLE
I think you have to return the mogrified x and h

### ISSUE THREAD

**Issue by fawazsammani** [RMichaelSwan/MogrifierLSTM#2]
Hi. You are calling `self.mogrify(xt,ht)` without returning the final mogrified xt and ht. So they aren't being changed in the forward function (only locally in the mogrify function). You haven't defined xt and ht as global class variables. Should that be the problem of why it isnt working?

**Comment by RMichaelSwan** [comment]
That's a great point, thank you for reviewing my code! I think I was trying to make use of the variables by reference, but there's a very good chance python is not treating them that way in this case. I'll put in the appropriate return statement and see if I can do another run through soon.

**Comment by RMichaelSwan** [comment]
Implemented and tested as of commit 07690d512944043434ed7c679fdfc0227a4b2255. Seems to be working now. I updated the readme with the results along with the notebook. Thanks again!
